name: mock_request
version: 1.0.3
description: Manufacture dart:io HttpRequests, HttpResponses, HttpHeaders, etc.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/mock_request
environment:
    sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  dart2_constant: ^1.0.0
  charcode: ">=1.0.0 <2.0.0"
dev_dependencies:
  angel_framework: ">=1.0.0-dev <2.0.0"
  http: ">=0.11.3 <0.12.0"
  test: ">=0.12.0 <0.13.0"