name: mock_request
version: 1.0.0
description: Mock dart:io HttpRequests, HttpResponses, HttpHeaders, etc.
author: Tobe O <thosakwe@gmail.com>
dependencies:
  charcode: ">=1.0.0 <2.0.0"
dev_dependencies:
  angel_framework: ">=1.0.0-dev <2.0.0"
  http: ">=0.11.3 <0.12.0"
  test: ">=0.12.0 <0.13.0"