name: mock_request
version: 1.0.6
description: Manufacture dart:io HttpRequests, HttpResponses, HttpHeaders, etc.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/mock_request
environment:
    sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  charcode: ">=1.0.0 <2.0.0"
dev_dependencies:
  angel_framework: ^2.0.0-alpha
  http: ^0.11.0
  test: ^1.0.0